##
# AdventOfCode2024Day5
#
# @file
# @version 0.1

AdventOfCode2024Day5: main.cpp build
	g++ -std=c++20 -g -Wall main.cpp -o ./build/AdventOfCode2024Day5

build:
	mkdir build

clean:
	rm -rf ./build


# end
